debug = false
key = "189rjfadoisfj8923fjio"


[[hosts]]
authority   = "127.0.0.1:3001"
bind_dn = "admin"
bind_pw = "admin"
base ="dc=example,dc=org"
scheme  = "ldaps"
interval = 3

[[hosts]]
authority   = "127.0.0.1:3002"
bind_dn = "admin"
bind_pw = "admin"
base ="dc=example,dc=org"
scheme  = "ldaps"
interval = 3

